# Generated by Django 3.2.14 on 2023-03-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sermon',
            options={'verbose_name_plural': 'Sermons'},
        ),
        migrations.AddField(
            model_name='sermon',
            name='image',
            field=models.ImageField(default='sermons/default.jpg', upload_to='sermons/'),
        ),
        migrations.AlterUniqueTogether(
            name='sermon',
            unique_together={('title', 'date')},
        ),
    ]
