# Generated by Django 3.2.14 on 2023-03-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20230327_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='audio',
            field=models.FileField(upload_to='media/sermons/'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='image',
            field=models.ImageField(default='sermons/default.jpg', upload_to='media/sermons/'),
        ),
    ]
