# Generated by Django 3.2.14 on 2023-04-03 14:23

from django.db import migrations, models
import pages.formatChecker


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_sermon_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sermon',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='sermon',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='sermons/', validators=[pages.formatChecker.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='image_desktop',
            field=models.ImageField(default='sermons/default.jpg', upload_to='sermons/desktop/image'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='image_mobile',
            field=models.ImageField(default='sermons/default.jpg', upload_to='sermons/mobile/image'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
